CREATE TABLE IF NOT EXISTS BATCH_COMMENT (
  JOB_EXEC_ID BIGINT NOT NULL ,
	JOB_ID BIGINT NOT NULL ,
	COMMENT VARCHAR(1024) NOT NULL,
	PRIMARY KEY (JOB_EXEC_ID, JOB_ID)
);
TRUNCATE TABLE BATCH_COMMENT;